version: '3'

services:
  clip:
    image: mtphotos-clip-search:onnx
    networks:
      - clip-net-onnx
    ports:
      - 8000:8000
    environment:
      - DBURL=postgresql://mtphotos:mtphotos@clip-db:5432/mtphotos
      - CLIP_API_KEY=YOUR_SECRET_API_KEY
      - MODEL=ViT-B-16
      - MODEL_PATH=/data/model
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/data

  clip-db:
    image: ankane/pgvector:v0.4.4
    container_name: pg
    restart: always
    # Not nessary to expose this port to host
    ports:
       - 8100:5432
    networks:
      - clip-net-onnx
    environment:
      - POSTGRES_USER=mtphotos
      - POSTGRES_PASSWORD=mtphotos
      - POSTGRES_DB=mtphotos
    volumes:
      - ./data/pg:/var/lib/postgresql/data


networks:
  clip-net-onnx:
